import env from "@/env";

/**
 * Verifies a token generated by Cloudflare Turnstile.
 * @param token The token sent alongside the request.
 * @returns `true` or `false`, depending on whether the token is valid.
 */
export async function verifyCaptcha(token = "0") {
  if (typeof token !== "string") return false;
  if (!token.length) return false;

  const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
    method: "post",
    headers: {
      "content-type": "application/x-www-form-urlencoded",
    },
    body: `secret=${env.turnstileSecretKey}&response=${token}`,
  });

  return (await res.json()).success;
}
