[phases.install]
cmds = [
  "nix-channel --add https://nixos.org/channels/nixos-23.05 nixpkgs",
  "nix-channel --update",
  "nix-env -iA nixpkgs.bun",
  "bun install"
]

[start]
cmd = "cd apps/server && bun start"
