export default {
  VITE_IS_PROD: import.meta.env.PROD,

  VITE_BASE_API: "https://staging-api.someonesays.io",
  VITE_DISCORD_CLIENT_ID: "1312178792256507924",

  VITE_TURNSTILE_SITE_KEY_INVISIBLE: "0x4AAAAAAA1KrqD-Q-njyu50",
  VITE_TURNSTILE_SITE_KEY_MANAGED: "0x4AAAAAAA1Krb5_9TKRUaKy",
};
