export default {
  VITE_IS_PROD: import.meta.env.PROD,

  VITE_BASE_API: import.meta.env.VITE_BASE_API,
  VITE_DISCORD_CLIENT_ID: import.meta.env.VITE_DISCORD_CLIENT_ID,

  VITE_TURNSTILE_SITE_KEY_INVISIBLE: import.meta.env.VITE_TURNSTILE_SITE_KEY_INVISIBLE,
  VITE_TURNSTILE_SITE_KEY_MANAGED: import.meta.env.VITE_TURNSTILE_SITE_KEY_MANAGED,
};
